export { stack, findIndexAt, anchorDelta } from './list.ts'
export { FIT_TOLERANCE } from './fit.ts'
export { shrinkwrap, balance, shrinkwrapRich, balanceRich } from './width.ts'
export type { WidthFit } from './width.ts'
export { measureTail, clamp, clampStats, fillLine } from './clamp.ts'
export type { Tail, ClampedLine, Clamped } from './clamp.ts'
